### ISSUE TITLE
jemallocator 0.1.9 is missing the 'stats' feature from jemalloc-sys

### ISSUE THREAD

**Issue by brson** [gnzlbg/jemallocator#112]
Not much else to say abut it. To turn on 'stats' one has to link directly to jemalloc-sys.

**Comment by brson** [comment]
Oh, right. This is fixed on master, so I'm just looking for a new release.

**Comment by brson** [comment]
Hm, master is at 0.3.0. Is the recommended way to use this crate by using it directly from git?

**Comment by gnzlbg** [comment]
I'll do a release.

**Comment by gnzlbg** [comment]
0.3 released

**Comment by brson** [comment]
Thanks @gnzlbg !
