### ISSUE TITLE
publish jemalloc-ctl 0.3.0

### ISSUE THREAD

**Issue by gnzlbg** [gnzlbg/jemallocator#113]
I'm holding publishing `jemalloc-ctl` until its reviewed. 

cc @sfackler

**Comment by thijsc** [comment]
Antyhing holding this back?

**Comment by gnzlbg** [comment]
This release has some major changes that have not been reviewed. Maybe the currently released version works for you as is, otherwise you can try using it from master and report if you find any issues.

**Comment by thijsc** [comment]
I'll try it out!

Main reason I asked btw is that using `jemalloc-ctl` currently locks down `jemallocator` to 0.1.9.

**Comment by brson** [comment]
What's the difference between the jemalloc-ctl in this repo and https://github.com/sfackler/jemalloc-ctl?

**Comment by sfackler** [comment]
@brson my crate's going to be deprecated in favor of this one.

The new API seems fine to me, sorry for the delay!

@gnzlbg should I just give you publish rights to jemalloc-ctl, or is there a github group I should use instead?

**Comment by gnzlbg** [comment]
You can give me publish access, but IIRC you are a collaborator of this repo, so you can also publish it yourself.

**Comment by sfackler** [comment]
Added you as a maintainer.

**Comment by gnzlbg** [comment]
Has been published!
