### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by sfackler** [gnzlbg/jemallocator#122]
It's unclear what commit the 0.3.0 release corresponds to, and what changes are in it from 0.1.

**Comment by sfackler** [comment]
Also, what happened to 0.2?

**Comment by gnzlbg** [comment]
https://github.com/gnzlbg/jemallocator/releases/tag/0.3.0

**Comment by gnzlbg** [comment]
> Also, what happened to 0.2?

Good question, can't recall. AFAICT it was never published.
