### ISSUE TITLE
Can't build from repo on MacOS X: configure: error: cannot find sources (Makefile.in) in jemallocator/target/debug/build/jemalloc-sys-a78a0bf5b0ae6246/out/jemalloc or ..

### ISSUE THREAD

**Issue by jorendorff** [gnzlbg/jemallocator#134]
I just cloned the repo and tried `cargo build`. It didn't work. Full build console output: https://gist.github.com/jorendorff/514255feb593b7a886c6f9087a8407d0

**Comment by sfackler** [comment]
You need to run `git submodule init`.

**Comment by jorendorff** [comment]
Of course! Thanks for the quick response, and I'm sorry for the noise.
